
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuvigdslneyjmvgghyax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dmlnZHNsbmV5am12Z2doeWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTYzOTQsImV4cCI6MjA2NTIzMjM5NH0.bVpi6PeqxiLinDmUfC4tUhYTruVPXBJivJnILraf2F8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
